### ISSUE TITLE
Migrate codebase to go 1.11 module

### ISSUE THREAD

**Issue by towe75** [hashicorp/nomad-driver-lxc#14]
Hi,

i'm working on your code base (see #12 and #13) and i'd like to improve the build environment to simplify further enhancements.

Can i add a go 1.11 go.mod configuration and remove the vendor/ folder or does this collide with any of your guides? I would file a pull request, of course.

Cheers,

Thomas

**Comment by tgross** [comment]
Done and tagged as 0.3.0 so we could ship #21
